package org.ontology.tcc.entities;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Ocupacao <br>
 * @version generated on Sat Sep 15 16:28:35 BRT 2018 by Julia
 */

public interface Ocupacao extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realiza
     */
     
    /**
     * Gets all property values for the realiza property.<p>
     * 
     * @returns a collection of values for the realiza property.
     */
    Collection<? extends Atividade> getRealiza();

    /**
     * Checks if the class has a realiza property value.<p>
     * 
     * @return true if there is a realiza property value.
     */
    boolean hasRealiza();

    /**
     * Adds a realiza property value.<p>
     * 
     * @param newRealiza the realiza property value to be added
     */
    void addRealiza(Atividade newRealiza);

    /**
     * Removes a realiza property value.<p>
     * 
     * @param oldRealiza the realiza property value to be removed.
     */
    void removeRealiza(Atividade oldRealiza);


    /* ***************************************************
     * Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#ocupacaoNome
     */
     
    /**
     * Gets all property values for the ocupacaoNome property.<p>
     * 
     * @returns a collection of values for the ocupacaoNome property.
     */
    Collection<? extends String> getOcupacaoNome();

    /**
     * Checks if the class has a ocupacaoNome property value.<p>
     * 
     * @return true if there is a ocupacaoNome property value.
     */
    boolean hasOcupacaoNome();

    /**
     * Adds a ocupacaoNome property value.<p>
     * 
     * @param newOcupacaoNome the ocupacaoNome property value to be added
     */
    void addOcupacaoNome(String newOcupacaoNome);

    /**
     * Removes a ocupacaoNome property value.<p>
     * 
     * @param oldOcupacaoNome the ocupacaoNome property value to be removed.
     */
    void removeOcupacaoNome(String oldOcupacaoNome);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
