package org.ontology.tcc.entities;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat Sep 15 16:28:32 BRT 2018 by Julia
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Atividade
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADE.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Atividade"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADECONDICAO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADECONDICAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoFinalidade
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADECONDICAOFINALIDADE.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADECONDICAOFINALIDADE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoFinalidade"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoLocal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADECONDICAOLOCAL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADECONDICAOLOCAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoLocal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoProduto
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADECONDICAOPRODUTO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADECONDICAOPRODUTO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoProduto"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoServico
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADECONDICAOSERVICO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADECONDICAOSERVICO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeCondicaoServico"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeElemento
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEELEMENTO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEELEMENTO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeElemento"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeFinalidade
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEFINALIDADE.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEFINALIDADE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeFinalidade"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeLocal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADELOCAL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADELOCAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeLocal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeProduto
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEPRODUTO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEPRODUTO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeProduto"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisito
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisito"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoDefinitivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITODEFINITIVO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITODEFINITIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoDefinitivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoFinalidadeDefinitivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOFINALIDADEDEFINITIVO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOFINALIDADEDEFINITIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoFinalidadeDefinitivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoFinalidadeVariavel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOFINALIDADEVARIAVEL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOFINALIDADEVARIAVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoFinalidadeVariavel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoLocalDefinitivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOLOCALDEFINITIVO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOLOCALDEFINITIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoLocalDefinitivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoLocalVariavel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOLOCALVARIAVEL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOLOCALVARIAVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoLocalVariavel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoProdutoDefinitivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOPRODUTODEFINITIVO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOPRODUTODEFINITIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoProdutoDefinitivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoProdutoVariavel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOPRODUTOVARIAVEL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOPRODUTOVARIAVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoProdutoVariavel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoServicoDefinitivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOSERVICODEFINITIVO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOSERVICODEFINITIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoServicoDefinitivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoServicoVariavel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOSERVICOVARIAVEL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOSERVICOVARIAVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoServicoVariavel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoVariavel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADEREQUISITOVARIAVEL.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADEREQUISITOVARIAVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeRequisitoVariavel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeServico
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADESERVICO.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADESERVICO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#AtividadeServico"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Classe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASSE.<p>
     * 
     */
    public static final OWLClass CLASS_CLASSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Classe"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#ConjuntoCNAE
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONJUNTOCNAE.<p>
     * 
     */
    public static final OWLClass CLASS_CONJUNTOCNAE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#ConjuntoCNAE"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Divisao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIVISAO.<p>
     * 
     */
    public static final OWLClass CLASS_DIVISAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Divisao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Grupo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GRUPO.<p>
     * 
     */
    public static final OWLClass CLASS_GRUPO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Grupo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Ocupacao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCUPACAO.<p>
     * 
     */
    public static final OWLClass CLASS_OCUPACAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Ocupacao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Secao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SECAO.<p>
     * 
     */
    public static final OWLClass CLASS_SECAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Secao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Subclasse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBCLASSE.<p>
     * 
     */
    public static final OWLClass CLASS_SUBCLASSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#Subclasse"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoFinalidadeSatisfeitaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONDICAOFINALIDADESATISFEITAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONDICAOFINALIDADESATISFEITAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoFinalidadeSatisfeitaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoLocalSatisfeitaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONDICAOLOCALSATISFEITAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONDICAOLOCALSATISFEITAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoLocalSatisfeitaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoProdutoSatisfeitaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONDICAOPRODUTOSATISFEITAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONDICAOPRODUTOSATISFEITAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoProdutoSatisfeitaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoSatisfeitaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONDICAOSATISFEITAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONDICAOSATISFEITAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoSatisfeitaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoServicoSatisfeitaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONDICAOSERVICOSATISFEITAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONDICAOSERVICOSATISFEITAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#condicaoServicoSatisfeitaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#elementoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ELEMENTOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ELEMENTOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#elementoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#especificoPara
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ESPECIFICOPARA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ESPECIFICOPARA = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#especificoPara"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#especificoParaProduto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ESPECIFICOPARAPRODUTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ESPECIFICOPARAPRODUTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#especificoParaProduto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#exceto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXCETO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXCETO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#exceto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoCondicao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXCETOCONDICAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXCETOCONDICAO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoCondicao"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoElemento
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXCETOELEMENTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXCETOELEMENTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoElemento"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoRequisito
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXCETOREQUISITO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXCETOREQUISITO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoRequisito"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#genericoPara
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERICOPARA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERICOPARA = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#genericoPara"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#genericoParaProduto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERICOPARAPRODUTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERICOPARAPRODUTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#genericoParaProduto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#permite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERMITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERMITE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#permite"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#permitidaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERMITIDAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERMITIDAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#permitidaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realiza
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REALIZA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REALIZA = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realiza"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realizadaPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REALIZADAPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REALIZADAPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realizadaPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoDefinitivoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITODEFINITIVOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITODEFINITIVOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoDefinitivoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoFinalidadeDefinitivoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOFINALIDADEDEFINITIVOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOFINALIDADEDEFINITIVOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoFinalidadeDefinitivoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoFinalidadeVariavelTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOFINALIDADEVARIAVELTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOFINALIDADEVARIAVELTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoFinalidadeVariavelTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoLocalDefinitivoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOLOCALDEFINITIVOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOLOCALDEFINITIVOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoLocalDefinitivoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoLocalVariavelTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOLOCALVARIAVELTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOLOCALVARIAVELTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoLocalVariavelTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoProdutoDefinitivoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOPRODUTODEFINITIVOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOPRODUTODEFINITIVOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoProdutoDefinitivoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoProdutoVariavelTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOPRODUTOVARIAVELTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOPRODUTOVARIAVELTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoProdutoVariavelTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoSatisfeitoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOSATISFEITOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOSATISFEITOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoSatisfeitoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoServicoDefinitivoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOSERVICODEFINITIVOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOSERVICODEFINITIVOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoServicoDefinitivoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoServicoVariavelTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOSERVICOVARIAVELTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOSERVICOVARIAVELTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoServicoVariavelTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoVariavelTidoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUISITOVARIAVELTIDOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUISITOVARIAVELTIDOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#requisitoVariavelTidoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZCONDICAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZCONDICAO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicao"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoFinalidade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZCONDICAOFINALIDADE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZCONDICAOFINALIDADE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoFinalidade"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoLocal
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZCONDICAOLOCAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZCONDICAOLOCAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoLocal"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoProduto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZCONDICAOPRODUTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZCONDICAOPRODUTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoProduto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoServico
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZCONDICAOSERVICO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZCONDICAOSERVICO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazCondicaoServico"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazRequisito
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFAZREQUISITO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFAZREQUISITO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#satisfazRequisito"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCONDICAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCONDICAO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicao"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoFinalidade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCONDICAOFINALIDADE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCONDICAOFINALIDADE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoFinalidade"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoLocal
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCONDICAOLOCAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCONDICAOLOCAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoLocal"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoProduto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCONDICAOPRODUTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCONDICAOPRODUTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoProduto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoServico
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCONDICAOSERVICO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCONDICAOSERVICO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoServico"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temElemento
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMELEMENTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMELEMENTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temElemento"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temExcecaoParaAtividade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMEXCECAOPARAATIVIDADE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMEXCECAOPARAATIVIDADE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temExcecaoParaAtividade"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temFinalidade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMFINALIDADE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMFINALIDADE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temFinalidade"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temGrupo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMGRUPO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMGRUPO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temGrupo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temLocal
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMLOCAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMLOCAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temLocal"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temProduto
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPRODUTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPRODUTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temProduto"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisito
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisito"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoDefinitivo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITODEFINITIVO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITODEFINITIVO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoDefinitivo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoFinalidadeDefinitivo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOFINALIDADEDEFINITIVO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOFINALIDADEDEFINITIVO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoFinalidadeDefinitivo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoFinalidadeVariavel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOFINALIDADEVARIAVEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOFINALIDADEVARIAVEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoFinalidadeVariavel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoLocalDefinitivo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOLOCALDEFINITIVO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOLOCALDEFINITIVO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoLocalDefinitivo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoLocalVariavel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOLOCALVARIAVEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOLOCALVARIAVEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoLocalVariavel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoProdutoDefinitivo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOPRODUTODEFINITIVO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOPRODUTODEFINITIVO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoProdutoDefinitivo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoProdutoVariavel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOPRODUTOVARIAVEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOPRODUTOVARIAVEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoProdutoVariavel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoServicoDefinitivo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOSERVICODEFINITIVO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOSERVICODEFINITIVO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoServicoDefinitivo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoServicoVariavel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOSERVICOVARIAVEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOSERVICOVARIAVEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoServicoVariavel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoVariavel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMREQUISITOVARIAVEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMREQUISITOVARIAVEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temRequisitoVariavel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temServico
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMSERVICO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMSERVICO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temServico"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temSubGrupo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMSUBGRUPO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMSUBGRUPO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temSubGrupo"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));
    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#atividadeDescricao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATIVIDADEDESCRICAO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATIVIDADEDESCRICAO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#atividadeDescricao"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#atividadeElementoDescricao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATIVIDADEELEMENTODESCRICAO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATIVIDADEELEMENTODESCRICAO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#atividadeElementoDescricao"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#conjuntoCodigo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONJUNTOCODIGO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONJUNTOCODIGO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#conjuntoCodigo"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#conjuntoDescricao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONJUNTODESCRICAO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONJUNTODESCRICAO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#conjuntoDescricao"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LABEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#label"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#ocupacaoNome
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OCUPACAONOME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OCUPACAONOME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#ocupacaoNome"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
