package org.ontology.tcc.entities.impl;

import org.ontology.tcc.entities.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAtividade <br>
 * @version generated on Sat Sep 15 16:28:32 BRT 2018 by Julia
 */
public class DefaultAtividade extends WrappedIndividualImpl implements Atividade {

    public DefaultAtividade(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#exceto
     */
     
    public Collection<? extends WrappedIndividual> getExceto() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_EXCETO,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasExceto() {
	   return !getExceto().isEmpty();
    }

    public void addExceto(WrappedIndividual newExceto) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_EXCETO,
                                       newExceto);
    }

    public void removeExceto(WrappedIndividual oldExceto) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_EXCETO,
                                          oldExceto);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoCondicao
     */
     
    public Collection<? extends AtividadeCondicao> getExcetoCondicao() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_EXCETOCONDICAO,
                                               DefaultAtividadeCondicao.class);
    }

    public boolean hasExcetoCondicao() {
	   return !getExcetoCondicao().isEmpty();
    }

    public void addExcetoCondicao(AtividadeCondicao newExcetoCondicao) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_EXCETOCONDICAO,
                                       newExcetoCondicao);
    }

    public void removeExcetoCondicao(AtividadeCondicao oldExcetoCondicao) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_EXCETOCONDICAO,
                                          oldExcetoCondicao);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoElemento
     */
     
    public Collection<? extends AtividadeElemento> getExcetoElemento() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_EXCETOELEMENTO,
                                               DefaultAtividadeElemento.class);
    }

    public boolean hasExcetoElemento() {
	   return !getExcetoElemento().isEmpty();
    }

    public void addExcetoElemento(AtividadeElemento newExcetoElemento) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_EXCETOELEMENTO,
                                       newExcetoElemento);
    }

    public void removeExcetoElemento(AtividadeElemento oldExcetoElemento) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_EXCETOELEMENTO,
                                          oldExcetoElemento);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#excetoRequisito
     */
     
    public Collection<? extends AtividadeRequisito> getExcetoRequisito() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_EXCETOREQUISITO,
                                               DefaultAtividadeRequisito.class);
    }

    public boolean hasExcetoRequisito() {
	   return !getExcetoRequisito().isEmpty();
    }

    public void addExcetoRequisito(AtividadeRequisito newExcetoRequisito) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_EXCETOREQUISITO,
                                       newExcetoRequisito);
    }

    public void removeExcetoRequisito(AtividadeRequisito oldExcetoRequisito) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_EXCETOREQUISITO,
                                          oldExcetoRequisito);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#permitidaPor
     */
     
    public Collection<? extends Subclasse> getPermitidaPor() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PERMITIDAPOR,
                                               DefaultSubclasse.class);
    }

    public boolean hasPermitidaPor() {
	   return !getPermitidaPor().isEmpty();
    }

    public void addPermitidaPor(Subclasse newPermitidaPor) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PERMITIDAPOR,
                                       newPermitidaPor);
    }

    public void removePermitidaPor(Subclasse oldPermitidaPor) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PERMITIDAPOR,
                                          oldPermitidaPor);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#realizadaPor
     */
     
    public Collection<? extends Ocupacao> getRealizadaPor() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_REALIZADAPOR,
                                               DefaultOcupacao.class);
    }

    public boolean hasRealizadaPor() {
	   return !getRealizadaPor().isEmpty();
    }

    public void addRealizadaPor(Ocupacao newRealizadaPor) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_REALIZADAPOR,
                                       newRealizadaPor);
    }

    public void removeRealizadaPor(Ocupacao oldRealizadaPor) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_REALIZADAPOR,
                                          oldRealizadaPor);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicao
     */
     
    public Collection<? extends AtividadeCondicao> getTemCondicao() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEMCONDICAO,
                                               DefaultAtividadeCondicao.class);
    }

    public boolean hasTemCondicao() {
	   return !getTemCondicao().isEmpty();
    }

    public void addTemCondicao(AtividadeCondicao newTemCondicao) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEMCONDICAO,
                                       newTemCondicao);
    }

    public void removeTemCondicao(AtividadeCondicao oldTemCondicao) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEMCONDICAO,
                                          oldTemCondicao);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoFinalidade
     */
     
    public Collection<? extends AtividadeCondicaoFinalidade> getTemCondicaoFinalidade() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEMCONDICAOFINALIDADE,
                                               DefaultAtividadeCondicaoFinalidade.class);
    }

    public boolean hasTemCondicaoFinalidade() {
	   return !getTemCondicaoFinalidade().isEmpty();
    }

    public void addTemCondicaoFinalidade(AtividadeCondicaoFinalidade newTemCondicaoFinalidade) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEMCONDICAOFINALIDADE,
                                       newTemCondicaoFinalidade);
    }

    public void removeTemCondicaoFinalidade(AtividadeCondicaoFinalidade oldTemCondicaoFinalidade) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEMCONDICAOFINALIDADE,
                                          oldTemCondicaoFinalidade);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoLocal
     */
     
    public Collection<? extends AtividadeCondicaoLocal> getTemCondicaoLocal() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEMCONDICAOLOCAL,
                                               DefaultAtividadeCondicaoLocal.class);
    }

    public boolean hasTemCondicaoLocal() {
	   return !getTemCondicaoLocal().isEmpty();
    }

    public void addTemCondicaoLocal(AtividadeCondicaoLocal newTemCondicaoLocal) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEMCONDICAOLOCAL,
                                       newTemCondicaoLocal);
    }

    public void removeTemCondicaoLocal(AtividadeCondicaoLocal oldTemCondicaoLocal) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEMCONDICAOLOCAL,
                                          oldTemCondicaoLocal);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoProduto
     */
     
    public Collection<? extends AtividadeCondicaoProduto> getTemCondicaoProduto() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEMCONDICAOPRODUTO,
                                               DefaultAtividadeCondicaoProduto.class);
    }

    public boolean hasTemCondicaoProduto() {
	   return !getTemCondicaoProduto().isEmpty();
    }

    public void addTemCondicaoProduto(AtividadeCondicaoProduto newTemCondicaoProduto) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEMCONDICAOPRODUTO,
                                       newTemCondicaoProduto);
    }

    public void removeTemCondicaoProduto(AtividadeCondicaoProduto oldTemCondicaoProduto) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEMCONDICAOPRODUTO,
                                          oldTemCondicaoProduto);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#temCondicaoServico
     */
     
    public Collection<? extends AtividadeCondicaoServico> getTemCondicaoServico() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEMCONDICAOSERVICO,
                                               DefaultAtividadeCondicaoServico.class);
    }

    public boolean hasTemCondicaoServico() {
	   return !getTemCondicaoServico().isEmpty();
    }

    public void addTemCondicaoServico(AtividadeCondicaoServico newTemCondicaoServico) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEMCONDICAOSERVICO,
                                       newTemCondicaoServico);
    }

    public void removeTemCondicaoServico(AtividadeCondicaoServico oldTemCondicaoServico) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEMCONDICAOSERVICO,
                                          oldTemCondicaoServico);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/gabriel/ontologies/2017/8/mei#atividadeDescricao
     */
     
    public Collection<? extends String> getAtividadeDescricao() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATIVIDADEDESCRICAO, String.class);
    }

    public boolean hasAtividadeDescricao() {
		return !getAtividadeDescricao().isEmpty();
    }

    public void addAtividadeDescricao(String newAtividadeDescricao) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATIVIDADEDESCRICAO, newAtividadeDescricao);
    }

    public void removeAtividadeDescricao(String oldAtividadeDescricao) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATIVIDADEDESCRICAO, oldAtividadeDescricao);
    }


}
